HOUSE PRICE PREDICTION:


1. Load the Boston housing dataset.
2. Preprocess the dataset (e.g., handle missing values, normalize features).
3. Split the dataset into training and testing sets.
4. Train a linear regression model using the training set.
5. Develop a GUI for user input of housing features.
6. Predict house prices based on user input using the trained model.
7. Visualize the prediction results using a ba

INDEPENDENT VARIABLES(X):

1.CRIM: Per capita crime rate by town.
2.ZN: Proportion of residential land zoned for lots over 25,000 sq. ft.
3.INDUS: Proportion of non-retail business acres per town.
4.CHAS: Charles River dummy variable (1 if tract bounds river; 0 otherwise).
5.NOX: Nitric oxide concentration (parts per 10 million).
6.RM: Average number of rooms per dwelling.
7.AGE: Proportion of owner-occupied units built prior to 1940.
8.DIS: Weighted distances to five Boston employment centers.
9.RAD: Index of accessibility to radial highways.
10.TAX: Full-value property tax rate per $10,000.
11.PTRATIO: Pupil-teacher ratio by town.
12.B: 1000(Bk - 0.63)^2 where Bk is the proportion of Black residents by town.
13.ISTAT: Percentage of lower status of the population.

DEPENDENT VARIABLE(Y):

1.MEDV: Median value of owner-occupied homes in $1000s (target variable).

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('BostonHousing.csv')

In [3]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
df.shape

(506, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [6]:
for column in df.columns:
    print(df[column].value_counts())
    print("*"*20)

crim
0.01501     2
14.33370    2
0.03466     1
0.03113     1
0.03049     1
           ..
1.51902     1
1.83377     1
1.46336     1
1.27346     1
0.04741     1
Name: count, Length: 504, dtype: int64
********************
zn
0.0      372
20.0      21
80.0      15
22.0      10
12.5      10
25.0      10
40.0       7
45.0       6
30.0       6
90.0       5
95.0       4
60.0       4
21.0       4
33.0       4
55.0       3
70.0       3
34.0       3
52.5       3
35.0       3
28.0       3
75.0       3
82.5       2
85.0       2
17.5       1
100.0      1
18.0       1
Name: count, dtype: int64
********************
indus
18.10    132
19.58     30
8.14      22
6.20      18
21.89     15
        ...
1.21       1
1.38       1
3.75       1
0.46       1
2.31       1
Name: count, Length: 76, dtype: int64
********************
chas
0    471
1     35
Name: count, dtype: int64
********************
nox
0.538    23
0.713    18
0.437    17
0.871    16
0.624    15
         ..
0.394     1
0.518     1
0.385     1
0.389     1
0.435     1
Name: count, Length: 81, dtype: int64
********************
rm
5.713    3
6.167    3
6.127    3
6.229    3
6.405    3
        ..
5.859    1
6.416    1
5.572    1
5.880    1
6.976    1
Name: count, Length: 446, dtype: int64
********************
age
100.0    43
95.4      4
96.0      4
98.2      4
97.9      4
         ..
58.4      1
74.4      1
73.4      1
33.1      1
89.3      1
Name: count, Length: 356, dtype: int64
********************
dis
3.4952    5
5.7209    4
5.2873    4
6.8147    4
5.4007    4
         ..
2.4220    1
2.1620    1
2.0407    1
1.9709    1
2.5050    1
Name: count, Length: 412, dtype: int64
********************
rad
24    132
5     115
4     110
3      38
6      26
2      24
8      24
1      20
7      17
Name: count, dtype: int64
********************
tax
666    132
307     40
403     30
437     15
304     14
      ...
285      1
198      1
256      1
244      1
313      1
Name: count, Length: 66, dtype: int64
********************
ptratio
20.2    140
14.7     34
21.0     27
17.8     23
19.2     19
17.4     18
18.6     17
19.1     17
18.4     16
16.6     16
21.2     15
15.2     13
13.0     12
17.9     11
20.9     11
18.7      9
19.6      8
19.7      8
17.6      7
16.4      6
16.9      5
16.0      5
20.1      5
18.0      5
16.1      5
19.0      4
18.3      4
16.8      4
18.2      4
14.9      4
18.5      4
17.0      4
18.9      3
12.6      3
14.8      3
15.3      3
15.9      2
15.6      2
18.8      2
22.0      2
13.6      1
15.1      1
17.3      1
21.1      1
14.4      1
15.5      1
Name: count, dtype: int64
********************
b
396.90    121
393.74      3
395.24      3
376.14      2
394.72      2
         ...
240.16      1
389.61      1
374.43      1
338.92      1
391.99      1
Name: count, Length: 357, dtype: int64
********************
lstat
7.79     3
14.10    3
6.36     3
18.13    3
8.05     3
        ..
3.32     1
1.92     1
1.73     1
6.43     1
7.88     1
Name: count, Length: 455, dtype: int64
********************
medv
50.0    16
25.0     8
22.0     7
21.7     7
23.1     7
        ..
32.9     1
34.6     1
30.3     1
33.3     1
8.1      1
Name: count, Length: 229, dtype: int64
********************

In [7]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [9]:
import tkinter as tk
from tkinter import messagebox
from tkinter import ttk
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

In [10]:
df = pd.read_csv('D:\\Quant\\House\\BostonHousing.csv')
X = df[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
y = df['medv']

In [11]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [12]:
def predict():
    # Get user inputs
    inputs = []
    for entry in entries:
        inputs.append(float(entry.get()))
    
    # Predict using the model
    global prediction
    prediction = model.predict([inputs])[0]
    
    # Display prediction
    messagebox.showinfo("Prediction", f"The predicted MEDV value is: {prediction}")

In [13]:
def visualize():
    # Get user inputs
    inputs = []
    for entry in entries:
        inputs.append(float(entry.get()))
    
    # Ensure the prediction is made
    try:
        prediction
    except NameError:
        messagebox.showwarning("Warning", "Please make a prediction first.")
        return
    
    # Plotting
    plot_prediction(inputs, prediction)

In [14]:
def plot_prediction(inputs, prediction):
    # Prepare plot data
    features = X.columns
    x_values = range(1, len(features) + 1)
    input_values = inputs
    
    # Create figure and plot
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.bar(x_values, input_values, label='Input Values', color='b', alpha=0.5)
    ax.scatter(len(features) + 1, prediction, color='r', marker='o', label='Predicted MEDV')
    
    ax.set_xlabel('Features')
    ax.set_ylabel('Values')
    ax.set_title('Input Values and Predicted MEDV')
    ax.set_xticks(list(x_values) + [len(features) + 1])
    ax.set_xticklabels(features.tolist() + ['Predicted MEDV'], rotation=45)
    
    ax.legend()
    
    # Create new window for plot
    new_window = tk.Toplevel(root)
    new_window.title("Prediction Graph")
    
    canvas = FigureCanvasTkAgg(fig, master=new_window)
    canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True)
    canvas.draw()

In [15]:
root = tk.Tk()
root.title("Machine Learning Prediction Model")

''

In [16]:
entries = []
for i, col in enumerate(X.columns):
    label = ttk.Label(root, text=col)
    label.grid(row=i, column=0, padx=10, pady=5)
    
    entry = ttk.Entry(root)
    entry.grid(row=i, column=1, padx=10, pady=5)
    
    entries.append(entry)

In [17]:
# Create Predict button
predict_button = ttk.Button(root, text="Predict", command=predict)
predict_button.grid(row=len(X.columns), columnspan=2, padx=10, pady=10)

# Create Visualize button
visualize_button = ttk.Button(root, text="Visualize", command=visualize)
visualize_button.grid(row=len(X.columns)+1, columnspan=2, padx=10, pady=10)

root.mainloop()